apiVersion: v1
kind: Service
metadata:
  name: iot-app-jpg-service
  labels:
    app: iot-app-jpg
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: iot-app-jpg
