version = 0.1
[default.deploy.parameters]
stack_name = "InternIoTPoC-backend"
resolve_s3 = true
s3_prefix = "InternIoTPoC-backend"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"intern-iot-poc-tf-backend\" DynamoDBTableName=\"InternIoTPoCTerraformLocks\""
image_repositories = []
