apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management # Official RabbitMQ image with management plugin
          ports:
            - containerPort: 5672 # RabbitMQ default port
            - containerPort: 15672 # RabbitMQ management UI port
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user" # Default username
            - name: RABBITMQ_DEFAULT_PASS
              value: "password" # Default password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - port: 5672
      targetPort: 5672
    - port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq
