name: Full Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to Perform"
        type: choice
        options:
          - Plan
          - Apply
          - Destroy
        required: true

jobs:
  terraform:
    name: Full Terraform Deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    steps:
      # Step 1: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      # Step 2: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 4: Write .tfvars File from GitHub Secrets
      - name: Write .tfvars File
        run: echo '${{ vars.TFVARS_FILE_JSON }}' > terraform.tfvars.json

      # Step 5: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 6: Check Terraform Formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Step 7: Terraform Plan (Plan or Apply)
      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'Plan' || github.event.inputs.action == 'Apply' }}
        run: terraform plan -var-file=terraform.tfvars.json -input=false

      # Step 8: Terraform Apply (Apply Only)
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'Apply' }}
        run: terraform apply -var-file=terraform.tfvars.json -auto-approve -input=false

      # Step 9: Terraform Plan (Destroy Only)
      - name: Terraform Plan (Destroy)
        if: ${{ github.event.inputs.action == 'Destroy' }}
        run: terraform plan -destroy -var-file=terraform.tfvars.json -input=false

      # Step 10: Terraform Destroy (Destroy Only)
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'Destroy' }}
        run: terraform apply -destroy -var-file=terraform.tfvars.json -auto-approve